# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs

PATH=$PATH:$HOME/bin:/sbin

export PATH

# setup LANG
export LANG="en_US.UTF-8"

# setup XTERM
export TERM="xterm-256color"

# setup EDITOR
export EDITOR=vim
